apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"nginx-bio-dev","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"nginx-bio-dev","servicePort":80},"path":"/bio"}]}}]}}
  name: nginx-bio-prod
  namespace: default
spec:
  rules:
  - host: www.adiannyramirez.com
    http:
      paths:
      - backend:
          serviceName: nginx-bio-prod
          servicePort: 80
        path: /
  - host: adiannyramirez.com
    http:
      paths:
      - backend:
          serviceName: nginx-bio-prod
          servicePort: 80
        path: /
